network:
  vlans:
    vlan.2257:
      addresses:
      - "10.145.204.75/26"
      routes:
        - to: 0.0.0.0/0
          via: "10.145.204.65"
      mtu: 1500
      id: 2257
      link: bond-uplink
      link-local: []
      nameservers:
        addresses:
        - 10.90.24.1
        - 10.90.24.17
        search:
        - sa2.ba.schiff.telekom.de
        - schiff.telekom.de
        - das-schiff.telekom.de
  bonds:
    bond-uplink:
      interfaces:
      - eno1
      - eno2
      parameters:
        mode: active-backup
        primary: eno1
        mii-monitor-interval: 1000
  ethernets:
    eno1:
      link-local: []
      mtu: 9100
    eno2:
      link-local: []
      mtu: 9100
  renderer: networkd
  version: 3