network:
    ethernets:
        id0:
            addresses:
            - 10.23.142.9/28
            gateway4: 10.23.142.1
            match:
                macaddress: 00:50:56:a1:19:a6
            nameservers:
                addresses:
                - 10.102.102.132
                - 10.102.102.133
                - 10.90.24.1
                search:
                - refsa2.bn.schiff.telekom.de
            set-name: eth0
            wakeonlan: true
        id1:
            addresses:
            - 10.23.134.134/28
            match:
                macaddress: 00:50:56:a1:50:32
            set-name: eth1
            wakeonlan: true
        id2:
            addresses:
            - 10.23.79.134/27
            match:
                macaddress: 00:50:56:a1:00:cc
            routes:
            -   metric: 100
                to: 10.108.180.101/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.108.180.117/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.23.75.224/30
                via: 10.108.231.158
            -   metric: 100
                to: 10.23.75.128/27
                via: 10.108.231.158
            -   metric: 100
                to: 192.168.113.100/31
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.49/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.50/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.47/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.48/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.184.47/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.184.48/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.185.49/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.185.50/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.185.220/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.108.183.20/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.108.183.4/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.140/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.184.134/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.185.134/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.180/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.183.181/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.184.180/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.185.180/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.185.181/32
                via: 10.108.231.158
            -   metric: 100
                to: 193.154.163.193/32
                via: 10.108.231.158
            -   metric: 100
                to: 193.254.163.201/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.181.134/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.182.134/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.182.220/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.182.222/32
                via: 10.108.231.158
            -   metric: 100
                to: 10.102.181.44/32
                via: 10.108.231.158
            set-name: eth2
            wakeonlan: true
        id3:
            addresses:
            - 10.23.79.118/28
            match:
                macaddress: 00:50:56:a1:22:7d
            routes:
            -   metric: 100
                to: 192.168.113.100/31
                via: 10.108.231.174
            set-name: eth3
            wakeonlan: true
    version: 2