network:
    dummies:
        dummy.underlay:
            link_local: []
            vrf: Vrf_underlay
            addresses:
                - 192.168.0.45/32
        dummy.cluster:
            link_local: []
            nameservers:
                addresses:
                - 10.90.24.1
                - 10.90.24.17
                search:
                - sa2.ba.schiff.telekom.de
                - schiff.telekom.de
                - das-schiff.telekom.de
            addresses:
                - 172.23.166.150/32
    ethernets:  
        ens1f0:
            link-local: ["ipv6"]
            emit-lldp: true
            vrf: Vrf_underlay
            virtual-function-count: 16
        ens1f1:
            link-local: ["ipv6"]
            emit-lldp: true
            vrf: Vrf_underlay
            virtual-function-count: 16
        ens2f0:
            link-local: ["ipv6"]
            emit-lldp: true
            vrf: Vrf_underlay
            virtual-function-count: 16
        ens2f1:
            link-local: ["ipv6"]
            emit-lldp: true
            vrf: Vrf_underlay
            virtual-function-count: 16
    version: 3
    renderer: networkd
    vrfs:
        Vrf_underlay:
            table: 1
    vxlans:
        vx.5000:
            description: "The Root of all hell"
            routes:
                - to: 10.0.0.0/8
                  via: 192.168.1.1
            parameters:
                vni: 5000
                local: 192.168.0.45
                mac-learning: false
    bridges:
        br.cluster:
            nameservers: {}
            link_local: []
            parameters:
                stp: false
            interfaces:
                - vx.5000
    additionals:
        10-default.link:
            - Match:
                - OriginalName: "vx*"
            - Link:
                - NamePolicy: "keep kernel database onboard slot path"
                - AlternativeNamesPolicy: "database onboard slot path"
                - MACAddressPolicy: "none"
        lo.network:
            - Match:
                - Name: "lo"
            - Network:
                - DHCP: "no"
                - IPv6AcceptRA: "no"
                - Address: "192.168.0.45/32"
        eth0.network:
            - Match:
                - Name: "eth0"
            - Network:
                - DHCP: "no"
                - IPv6AcceptRA: "no"
                - DNS: 8.8.8.8
                - DNS: 8.8.4.4
                - Domains: "telekom.local"
                - Address: "10.0.2.2/24"
                - Gateway: "10.0.2.15"
        eth1.network:
            - Match:
                - Name: "eth1"
            - Network:
                - VRF: "tenant_vrf"
                - DHCP: "no"
                - IPv6AcceptRA: "yes"
                - LinkLocalAddressing: "ipv6"
                - LLDP: "routers-only"
                - EmitLLDP: "yes"
                - LinkLocalAddressing: "ipv6"
                # - Address: "fd03:0:a802::73/127"
        eth2.network:
            - Match:
                - Name: "eth2"
            - Network:
                - VRF: "tenant_vrf"
                - DHCP: "no"
                - IPv6AcceptRA: "yes"
                - LLDP: "routers-only"
                - EmitLLDP: "yes"
                - LinkLocalAddressing: "ipv6"
                # - Address: "fd03:0:a802::75/127"
        tenant_vrf.network: 
            - Match:
                - Name: "tenant_vrf"
        br-vxl10.network:  
            - Match:
                - Name: "br-vxl10"
            - Network:
                - VRF: "tenant_vrf"
                - VXLAN: "vxl10"
                - LinkLocalAddressing: "no"
        tenant_vrf.netdev:
            - NetDev: 
                - Name: "tenant_vrf"
                - Kind: "vrf"
            - VRF:
                - Table: "5000"
        vxl10.netdev: 
            - NetDev:
                - Name: "vxl10"
                - Kind: "vxlan"
            - VXLAN:
                - Id: "5000" # The VXLAN ID to use
                - DestinationPort: "4789" # DestinationPort**
                - Local: 192.168.0.45
                - MacLearning: "no"
        br-vxl10.netdev:
            - NetDev:
                - Name: "br-vxl10"
                - Kind: "bridge"
            - Bridge:
                - STP: "no"
