network:
  dummies:
    dum.underlay:
      description: "Loopback IP for Underlay Network"
      link-local: []
      vrf: Vrf_underlay
      addresses:
        - 192.168.0.45/32
    dum.cluster:
      description: "Loopback IP for the K8s Node"
      link-local: []
      nameservers:
        addresses:
        - 10.90.24.1
        - 10.90.24.17
        search:
        - sa2.ba.schiff.telekom.de
        - schiff.telekom.de
        - das-schiff.telekom.de
      addresses:
        - 172.23.166.150/32
  ethernets:  
    ens1f0:
      emit-lldp: true
      accept-ra: false
      vrf: Vrf_underlay
      virtual-function-count: 16
    ens1f1:
      emit-lldp: true
      accept-ra: false
      vrf: Vrf_underlay
      virtual-function-count: 16
    ens2f0:
      emit-lldp: true
      vrf: Vrf_underlay
      virtual-function-count: 16
    ens2f1:
      emit-lldp: true
      vrf: Vrf_underlay
      virtual-function-count: 16
  version: 3
  renderer: networkd
  vrfs:
    Vrf_underlay:
      table: 2
      link-local: []
  vxlans:
    vx.5000:
      description: "The connectivity to the Customer Overlay"
      link: dum.underlay
      link_local: []
      parameters:
        vni: 5000
        local: 192.168.0.45
        mac-learning: false
        hairpin: true
  bridges:
    br.cluster:
      description: "This handles All Networks of the Cluster"
      link_local: []
      parameters:
        stp: false
      interfaces:
        - vx.5000
  additionals:
    10-default.link:
      - Match:
        - OriginalName: "vx.*"
      - Link:
        - NamePolicy: "keep kernel database onboard slot path"
        - AlternativeNamesPolicy: "database onboard slot path"
        - MACAddressPolicy: "none"
